"use client";

import { Fragment, useEffect, useRef } from "react";
import { sitePath } from "./site-path";
import { projectPages } from "./wiki-data";

function FlowArrow({ vertical = false }: { vertical?: boolean }) {
  return <span className={`flow-arrow${vertical ? " vertical" : ""}`} aria-hidden="true"><svg viewBox="0 0 100 30"><path className="flow-base" d="M3 15H84" /><path className="flow-current" d="M3 15H84" /><path className="flow-tip" d="M78 5L94 15L78 25" /></svg></span>;
}

function BranchLines({ merge = false }: { merge?: boolean }) {
  const paths = merge ? ["M24 0V35H50V65", "M76 0V35H50V65"] : ["M50 0V30H24V65", "M50 0V30H76V65"];
  return <svg className="branch-lines" viewBox="0 0 100 70" preserveAspectRatio="none" aria-hidden="true">{paths.map(d => <Fragment key={d}><path className="flow-base" d={d} vectorEffect="non-scaling-stroke" /><path className="flow-current" d={d} vectorEffect="non-scaling-stroke" /></Fragment>)}{(merge ? [50] : [24, 76]).map(x => <path key={x} className="branch-tip" d={`M${x-2} 61L${x} 68L${x+2} 61`} vectorEffect="non-scaling-stroke" />)}</svg>;
}

export function HomeStory() {
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!root.current || !("IntersectionObserver" in window)) return;
    const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.target.classList.toggle("is-in-view", entry.isIntersecting)), { threshold: .08 });
    root.current.querySelectorAll(".story-section").forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  return <div className="home-story" ref={root}>
    <section className="story-section editing-section" id="slide-2" aria-labelledby="editing-title">
      <img className="home-painted-art painted-dna" src={sitePath("/assets/illustrations-20261005/home-dna-ribbon.webp")} width={1200} height={600} loading="lazy" alt="" aria-hidden="true" />
      <h2 id="editing-title">Editing small changes is no longer the hardest part</h2>
      <div className="editing-copy"><p className="serif-copy">Our interest in large-fragment DNA editing led us to ISCro4.</p><p>With Biomni’s guidance and our own literature review, we compared emerging DNA-editing systems and chose ISCro4 for directed evolution. The project tested whether its recombination activity could be further improved in <i>E. coli</i>.</p><p>Research interest → Literature review → Experimental validation</p></div>
      <div className="editing-flow">
        <img className="research-photo raised" src={sitePath("/assets/research.webp")} alt="Clinical researchers caring for a child" />
        <FlowArrow />
        <div className="precision-card raised"><h3>Nucleotide-scale precision</h3><div className="nucleotide-grid" aria-label="DNA bases with the C G pair highlighted">{["AT", "TA", "GC", "CG", "AT", "GC"].map((pair, i) => <span key={i} className={i === 3 ? "selected-base" : ""}>{pair[0]}<br />{pair[1]}</span>)}</div><p>Excellent for small changes</p></div>
        <FlowArrow />
        <div className="cargo-card raised"><h3>Gene-sized DNA cargo</h3><div className="cargo-diagram"><span>LARGE DNA<small>&gt; 1 kb</small></span><svg className="cargo-barrier" viewBox="0 0 90 100" aria-hidden="true"><path d="M8 20H50L86 50L50 80H8Z" fill="#f7a332"/><path d="M16 12L35 87L56 12" fill="none" stroke="#c54c51" strokeWidth="6"/></svg></div><p>Precise insertion remains difficult</p></div>
      </div>
    </section>

    <section className="story-section challenge-section story-columns" id="slide-3" aria-labelledby="challenge-title">
      <img className="challenge-backdrop-art" src={sitePath("/assets/updates-20261008/home-challenge-workbench.png")} width={1672} height={941} loading="lazy" alt="" aria-hidden="true" />
      <div className="diagram-panel cross-host-panel"><h3>From published data to experiment</h3><div className="host-transfer"><div className="host-card raised"><svg className="cell-symbol" viewBox="0 0 160 120" aria-hidden="true"><circle cx="80" cy="60" r="48" fill="#e8ddf4" stroke="#7040a3" strokeWidth="4"/><g fill="#7040a3"><circle cx="62" cy="49" r="6"/><circle cx="89" cy="38" r="5"/><circle cx="92" cy="74" r="7"/></g></svg><h4>Published DMS</h4><p>Deep mutational scan</p></div><div className="transfer-question"><span>?</span><FlowArrow /></div><div className="host-card raised"><svg className="cell-symbol" viewBox="0 0 160 120" aria-hidden="true"><ellipse cx="80" cy="60" rx="64" ry="38" fill="#def0e9" stroke="#287d72" strokeWidth="4"/><path d="M28 62C52 30 106 92 134 55" fill="none" stroke="#f7a332" strokeWidth="5"/></svg><h4><em>E. coli</em></h4><p>DNA deletion assay</p></div></div>
        <div className="mutation-card raised"><h4>Engineered parent</h4><div className="mutation-badges"><span>S30T</span><span>P54Q</span><span>S243H</span></div><p>Can additional single mutations improve activity?</p><p>Can an AI agent help a student team test them?</p></div>
      </div>
      <div className="challenge-copy"><h2 id="challenge-title">The Challenge</h2><p className="serif-copy">Our starting construct was the previously reported ISCro4(S30T/P54Q/S243H) variant, not wild-type ISCro4.</p><p className="serif-copy">Biomni helped us troubleshoot plasmid construction, select ten DMS-nominated mutations, and design primers. Its suggestions were checked through literature review and experiments.</p><img className="builder-mascot" src={sitePath("/assets/bridge-builder.png")} alt="ISCro4 mascot connecting two DNA strands" /><p className="orange-label">So we asked:</p><p className="challenge-question">Can we improve ISCro4 recombination activity, and can an AI scientific agent help a high school team complete directed evolution?</p></div>
    </section>

    <section className="story-section bridge-section story-columns" id="slide-4" aria-labelledby="bridge-title"><div><h2 id="bridge-title">Meet ISCro4</h2><div className="bridge-copy"><p>ISCro4 is a compact, RNA-guided bridge recombinase.</p><p>Its bridge RNA uses two programmable modules:<br />TBL recognizes target DNA; DBL recognizes donor DNA.</p><p>Together they assemble both DNA substrates for direct recombination without relying on HDR.<br />Our measured outcome: plasmid-borne DNA deletion in <em>E. coli</em>, not genomic integration or inversion.</p></div></div><img className="molecular-diagram raised" src={sitePath("/assets/iscro4-bridge.webp")} alt="A programmable molecular bridge: TBL and DBL bring target and donor DNA into one ISCro4 synaptic complex" /></section>

    <section className="story-section strategy-section story-columns" id="slide-5" aria-labelledby="strategy-title"><div className="strategy-copy"><h2 id="strategy-title">From an Engineered Parent to A225S</h2><p className="orange-label strategy-sequence">BASELINE → DMS CANDIDATES → qPCR → A225S</p><p>Starting point: ISCro4(S30T/P54Q/S243H).</p><p>Protein engineering<br />Screen ten DMS-nominated single mutations, excluding the three positions already changed in the parent.</p><p>Assay development<br />Replace leaky chloramphenicol selection with a quantitative qPCR-based DNA deletion assay.</p><p>Outcome: A225S showed a larger ΔCq than the engineered parent; one positive hit among ten candidates.</p><img className="home-painted-art painted-lab" src={sitePath("/assets/illustrations-20261005/home-petri-pipette.webp")} width={800} height={800} loading="lazy" alt="" aria-hidden="true" /></div><div className="diagram-panel dual-track"><h3>Protein engineering and assay development</h3><div className="baseline-node raised"><strong>Engineered parent</strong><span>S30T + P54Q + S243H</span></div><BranchLines /><div className="track-cards"><div className="track-card raised"><span className="track-badge purple">A</span><h4>Protein engineering</h4><p>DMS-guided substitutions</p><p>Single-mutant screening</p><p>Ten candidate mutations</p></div><div className="track-card raised"><span className="track-badge teal">B</span><h4>Assay development</h4><p>Leaky antibiotic selection</p><p>Two-plasmid deletion assay</p><p>Parent and E60Q controls</p></div></div><BranchLines merge /><div className="qpcr-node raised"><strong>DNA deletion qPCR</strong><span>3 independent colonies × 2 technical replicates</span></div><p className="target-label">A225S: improved activity relative to the engineered parent</p></div></section>

<section className="story-section evidence-section" id="slide-6" aria-labelledby="evidence-title"><div className="explore-copy"><h2 id="evidence-title">Let’s Explore<br />ISCro4 Evolution!</h2><img className="explore-mascot" src={sitePath("/assets/rna-progress.png")} alt="Bridge RNA mascot" /><div className="question-photo"><div><h3>Core Question</h3><p>Can mutation stacking and accessory proteins jointly improve ISCro4/MM168 inversion activity in <em>E. coli</em>?</p></div><img className="petri-photo raised" src={sitePath("/assets/petri-dish.jpeg")} alt="Bacterial colonies in a petri dish" /></div></div><div className="diagram-panel evidence-panel"><h3>From hypothesis to evidence</h3><div className="evidence-flow">{[{name:"PARENT",sub:"three mutations",caption:"Starting construct",tone:"green"},{name:"DMS",sub:"ten candidates",caption:"Select mutations",tone:"purple"},{name:"qPCR",sub:"DNA deletion",caption:"Measure activity",tone:"teal"},{name:"A225S",sub:"positive hit",caption:"Improved over parent",tone:"orange"}].map((step,i)=><Fragment key={step.name}>{i>0&&<FlowArrow/>}<div className="evidence-step"><div className={`evidence-orb ${step.tone}`}><strong>{step.name}</strong><span>{step.sub}</span></div><h4>{step.caption}</h4></div></Fragment>)}</div><div className="core-question raised"><h4>What the results establish</h4><p>A225S improved plasmid-borne DNA deletion activity in <em>E. coli</em>. Genomic integration, maximum payload size, editing fidelity and mammalian-cell activity remain to be tested.</p></div><p className="evidence-caption">Only single mutations were evaluated; combining mutations and structural modeling are future work.</p></div></section>
<footer className="story-footer"><a className="story-footer-link" href={sitePath("/members")}><h3>About US</h3><p>Meet the people behind VCA-Prudens</p></a><a className="story-footer-link" href={sitePath("/description")}><h3>About Topic</h3><p>Biomni-assisted, DMS-guided directed evolution of ISCro4.</p></a><nav className="footer-quicklinks" aria-labelledby="quicklinks-title"><h3 id="quicklinks-title">Quicklinks</h3><ul>{projectPages.map(page => <li key={page.slug}><a href={sitePath("/" + page.slug)}>{page.label}</a></li>)}</ul></nav><div><h3>Contact US</h3><p>Connect with VCA-Prudens</p><a href="mailto:mo202505@163.com">mo202505@163.com</a></div><p className="footer-mobile-note">This Wiki is also available on mobile devices.</p></footer>
  </div>;
}
